import { Vehicle } from '../types';

export const VEHICLES: Vehicle[] = [
  {
    id: '1',
    auctionNo: '74678761320',
    name: 'Honda Amaze 1.2 SXI -VTEC',
    year: 2015,
    registrationNo: 'GJ 19 XXXX',
    location: 'Ahmedabad East',
    ownerType: '1st Owner',
    kmDriven: '102131km',
    fuelType: 'CNG+Petrol',
    highestBid: 1235000,
    fairMarketValue: 1800000,
    image: 'https://i.ibb.co/hFbDpqtY/images-1.jpg',
    timeLeftSeconds: 44744,
    isAcceptingBids: true,
    transmission: 'Manual',
  },
  {
    id: '2',
    auctionNo: '74678761321',
    name: 'Honda Amaze 1.2 SXI -VTEC',
    year: 2015,
    registrationNo: 'GJ 19 XXXX',
    location: 'Ahmedabad East',
    ownerType: '1st Owner',
    kmDriven: '102131km',
    fuelType: 'CNG+Petrol',
    highestBid: 1235000,
    fairMarketValue: 1800000,
    image: 'https://i.ibb.co/9mnyqzkd/images.jpg',
    timeLeftSeconds: 18744,
    isAcceptingBids: true,
    transmission: 'Manual',
  },
  {
    id: '3',
    auctionNo: '74678761322',
    name: 'Maruti Suzuki Swift VXI',
    year: 2018,
    registrationNo: 'MH 12 XXXX',
    location: 'Mumbai',
    ownerType: '2nd Owner',
    kmDriven: '42300km',
    fuelType: 'Petrol',
    highestBid: 420000,
    fairMarketValue: 470000,
    image: 'https://i.ibb.co/hFbDpqtY/images-1.jpg',
    timeLeftSeconds: 19330,
    isAcceptingBids: true,
    transmission: 'Manual',
  },
  {
    id: '4',
    auctionNo: '74678761323',
    name: 'Hyundai Creta 1.4 S+',
    year: 2019,
    registrationNo: 'TN 09 XXXX',
    location: 'Chennai',
    ownerType: '1st Owner',
    kmDriven: '55600km',
    fuelType: 'Diesel',
    highestBid: 890000,
    fairMarketValue: 950000,
    image: 'https://i.ibb.co/9mnyqzkd/images.jpg',
    timeLeftSeconds: 4845,
    isAcceptingBids: false,
    transmission: 'Manual',
  },
];

export const TABS = [
  { id: 'live', label: 'Live', count: 13 },
  { id: 'c2b', label: 'C2B', count: 13 },
];

export const PLAY_STORE_URL =
  'https://play.google.com/store/apps/details?id=com.caryanams.store';
